import { Phone } from "lucide-react";
import { useState } from "react";
import { BookingDialog } from "./BookingDialog";
import { Button } from "./Button";
import { ExperienceGrid, Eyebrow, FinalCta, GalleryGrid, LocationsGrid, SectionHeading, SpaCards } from "./Sections";
import { images } from "@/data/site";
import contactMoment from "@/assets/contact-moment.jpg";

function splitTitle(title: string): { first: string; rest: string } { const idx = title.indexOf(". "); if (idx === -1) return { first: title, rest: "" }; return { first: title.slice(0, idx + 1), rest: title.slice(idx + 2) }; }

export function PageHero({ eyebrow, title, text, image = images.hero }: { eyebrow: string; title: string; text: string; image?: string }) { const { first, rest } = splitTitle(title); return <section className="page-hero overflow-hidden"><div className="container-shell grid items-center gap-14 lg:grid-cols-12"><div className="relative z-10 lg:col-span-5"><div className="flex items-center gap-4"><span aria-hidden="true" className="h-px w-10 shrink-0 bg-gold" /><Eyebrow>{eyebrow}</Eyebrow></div><h1 className="mt-7 max-w-2xl font-serif text-[3.3rem] leading-[1.06] tracking-[-0.01em] text-primary sm:text-7xl lg:text-[5.4rem]">{first}{rest && <> <span className="italic text-primary/85">{rest}</span></>}</h1><span aria-hidden="true" className="mt-8 block h-px w-16 bg-gold/50" /><p className="mt-6 max-w-md text-lg font-light leading-8 text-muted-foreground">{text}</p></div><div className="relative lg:col-span-7"><div className="media-frame-lg aspect-[4/3] shadow-elevated"><img src={image} alt="ADWITYA WELLNESS atmosphere" className="size-full object-cover" /></div><span className="absolute -bottom-6 right-4 font-serif text-5xl italic text-primary/20 sm:text-7xl">ADWITYA</span></div></div></section>; }

export function AboutPage() { const [book, setBook] = useState(false); return <><PageHero eyebrow="About ADWITYA" title="Wellness with Intention." text="An introduction to the parent wellness brand and its shared belief in thoughtful care, calm and restoration." image={images.treatment}/><section className="section"><div className="container-shell grid gap-14 lg:grid-cols-2"><SectionHeading eyebrow="Our brand story" title="A considered approach to wellbeing" text="ADWITYA WELLNESS brings together three wellness destinations in Rajkot, united by one philosophy of calm, considered care."/><div className="space-y-10">{[["Our Philosophy","True wellness begins when you pause, breathe and reconnect with yourself."],["Our Approach","Each experience is designed around individual comfort, considered touch and an atmosphere of ease."],["Our Commitment","We are committed to thoughtful experiences, welcoming spaces and personal wellbeing."]].map(([h,p])=><div key={h} className="border-l border-gold pl-6"><h3 className="font-serif text-3xl text-primary">{h}</h3><p className="mt-2 leading-7 text-muted-foreground">{p}</p></div>)}</div></div></section><section className="section bg-muted"><div className="container-shell"><SectionHeading eyebrow="Three Wellness Spaces" title="One philosophy, expressed three ways"/><SpaCards/></div></section><FinalCta onBook={()=>setBook(true)}/><BookingDialog open={book} onOpenChange={setBook}/></>; }
export function SpasPage() { const [book,setBook]=useState(false); return <><PageHero eyebrow="Our Wellness Spaces" title="Three Spaces. One Wellness Philosophy." text="Discover Ganga Spa, Amore Wellness and Sattva Wellness—each with its own atmosphere and approach to relaxation."/><section className="section"><div className="container-shell"><SpaCards/></div></section><FinalCta onBook={()=>setBook(true)}/><BookingDialog open={book} onOpenChange={setBook}/></>; }
export function ExperiencesPage() { const [book,setBook]=useState(false); return <><PageHero eyebrow="Wellness Treatments" title="Your Wellness, Your Way" text="From restorative massages to immersive rituals, discover experiences created to help you slow down and reconnect." image={images.hammam}/><section className="section"><div className="container-shell"><ExperienceGrid/></div></section><FinalCta onBook={()=>setBook(true)}/><BookingDialog open={book} onOpenChange={setBook}/></>; }
export function GalleryPage() { return <><PageHero eyebrow="A Glimpse Into Our World" title="Step Into Our World" text="A glimpse of the spaces, textures and details across our wellness destinations." image={images.details}/><section className="section pt-0"><div className="container-shell"><GalleryGrid/></div></section></>; }
export function LocationsPage() { return <><PageHero eyebrow="Visit Us" title="Our Wellness Destinations" text="Three wellness destinations across Rajkot, each with its own address, phone number, opening hours and directions."/><section className="section"><div className="container-shell"><LocationsGrid/><p className="mt-8 text-center text-sm text-muted-foreground">Addresses, phone numbers and opening hours are verified for all three spas.</p></div></section></>; }
export function ContactPage() { const [book,setBook]=useState(false); return <><PageHero eyebrow="Contact" title="We’re Here for Your Wellness Journey" text="Choose a wellness space and reach out — we are happy to help you plan your visit." image={images.treatment}/><section className="section"><div className="container-shell grid gap-12 lg:grid-cols-2"><div><SectionHeading eyebrow="Connect With Us" title="Plan a moment for yourself" text="ADWITYA WELLNESS brings together three distinctive wellness destinations."/><a href="tel:+917567718839" className="mt-8 flex w-fit min-h-14 items-center gap-3 rounded-full border border-border bg-background px-5 py-2.5 transition-all duration-300 hover:-translate-y-0.5 hover:shadow-soft"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-sage text-primary"><Phone className="size-4" /></span><span className="min-w-0"><span className="block text-[0.6rem] font-medium uppercase tracking-[0.16em] text-muted-foreground">Tap to call</span><strong className="block text-base font-medium text-primary">+91 75677 18839</strong></span></a><Button className="mt-6" onClick={()=>setBook(true)}>Request Appointment</Button></div><div className="relative"><div className="media-frame-lg aspect-[4/5] max-h-[640px] w-full overflow-hidden shadow-elevated"><img src={contactMoment} alt="A quiet wellness moment — tea and rest by the window" loading="lazy" width={1024} height={1280} className="size-full object-cover" /></div><span className="absolute -bottom-6 left-4 font-serif text-5xl italic text-primary/20 sm:text-6xl">Pause</span></div></div></section><BookingDialog open={book} onOpenChange={setBook}/></>; }

