import { Link } from "@tanstack/react-router";
import { ArrowRight, ChevronLeft, ChevronRight, Clock3, MapPin, Phone, Sparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "./Button";
import { experiences, images, spas } from "@/data/site";
import gangaLogoAsset from "@/assets/spa-logos/ganga-logo.png.asset.json";
import amoreLogoAsset from "@/assets/spa-logos/amore-logo.png.asset.json";
import sattvaLogoAsset from "@/assets/spa-logos/sattva-logo.png.asset.json";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
export function SectionHeading({ eyebrow, title, text, align = "left" }: { eyebrow: string; title: string; text?: string; align?: "left" | "center" }) { return <div className={align === "center" ? "mx-auto max-w-3xl text-center" : "max-w-2xl"}><Eyebrow>{eyebrow}</Eyebrow><h2 className="section-title mt-3">{title}</h2>{text && <p className="mt-5 text-base leading-8 text-muted-foreground sm:text-lg">{text}</p>}</div>; }

const spaLogos = {
  "ganga-spa": gangaLogoAsset.url,
  "amore-wellness": amoreLogoAsset.url,
  "sattva-wellness": sattvaLogoAsset.url,
} satisfies Record<(typeof spas)[number]["slug"], string>;

export function SpaCards() { return <div className="mt-14 grid gap-6 md:grid-cols-3">{spas.map((spa, index) => <Link to={`/${spa.slug}` as "/ganga-spa"} key={spa.slug} aria-label={`Explore ${spa.name}`} className="group surface-card block transition-all duration-500 hover:-translate-y-1.5 hover:shadow-soft focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary"><div className="relative aspect-[4/5] media-frame overflow-hidden"><img src={spa.heroImage} alt={`${spa.name} wellness atmosphere`} loading="lazy" className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.045]" /><div className="absolute inset-0 bg-gradient-to-b from-primary/10 via-transparent to-primary/55" /><div className="absolute inset-0 grid place-items-center px-8"><img src={spaLogos[spa.slug]} alt={`${spa.name} logo`} className={`w-auto object-contain drop-shadow-lg transition-transform duration-500 group-hover:scale-105 ${spa.slug === "ganga-spa" ? "h-28 max-w-[85%]" : "h-32 max-w-[75%]"}`} /></div><span className="absolute left-5 top-5 rounded-full bg-background/90 px-4 py-2 text-[0.6rem] font-semibold uppercase tracking-[0.14em] text-primary backdrop-blur-md">Destination 0{index + 1}</span></div><div className="px-6 pb-7 pt-6"><h3 className="font-serif text-3xl text-primary">{spa.name}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{spa.description}</p><p className="mt-4 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4 text-gold" /> {spa.location}</p><span className="mt-6 inline-flex items-center gap-2 text-[0.68rem] font-medium uppercase tracking-[0.16em] text-primary">Explore <ArrowRight className="size-4 transition-transform duration-300 group-hover:translate-x-1" /></span></div></Link>)}</div>; }

export function ExperienceGrid({ limit }: { limit?: number }) { return <div className="mt-14 grid gap-x-8 gap-y-14 sm:grid-cols-2 lg:grid-cols-3">{experiences.slice(0, limit).map((item, index) => <article className={`group ${index % 3 === 1 ? "lg:translate-y-10" : ""}`} key={item.name}><div className={`${index % 3 === 1 ? "aspect-[4/5]" : "aspect-[5/4]"} media-frame`}><img src={item.image} alt={`${item.name} at ADWITYA WELLNESS`} loading="lazy" className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.035]" /></div><p className="mt-5 text-[0.65rem] font-medium uppercase tracking-[0.2em] text-gold">{item.tag}</p><div className="mt-2 flex items-baseline justify-between pb-2"><h3 className="font-serif text-3xl text-primary">{item.name}</h3><span className="text-xs text-muted-foreground">0{index + 1}</span></div><p className="mt-4 text-sm leading-7 text-muted-foreground">{item.description}</p></article>)}</div>; }

export function LocationsGrid() { return <div className="mt-14 grid gap-6 lg:grid-cols-3">{spas.map(spa => { const verified = spa.contactVerified === true; return <article key={spa.slug} className="group surface-card p-5 transition-all duration-500 hover:-translate-y-1 hover:shadow-soft"><div className="aspect-[16/10] media-frame"><img src={spa.heroImage} alt={`${spa.name} location`} loading="lazy" className="size-full object-cover transition-transform duration-700 group-hover:scale-[1.03]" /></div><div className="pt-6"><h3 className="font-serif text-3xl text-primary">{spa.name}</h3><p className="mt-2 flex items-center gap-2 text-sm text-muted-foreground"><MapPin className="size-4 text-gold" /> {spa.location}</p><div className="mt-5 grid gap-3 border-y border-border py-5 text-sm text-muted-foreground"><p className="flex items-start gap-2"><MapPin className="mt-1 size-4 shrink-0" /> {spa.address}</p><p className="flex items-center gap-2"><Clock3 className="size-4" /> {spa.hours}</p><p className="flex items-center gap-2"><Phone className="size-4" /> {spa.phone}</p></div><div className="mt-5 flex flex-wrap gap-4 text-[0.68rem] font-medium uppercase tracking-[0.16em] text-primary"><a href={spa.googleMapsUrl} target="_blank" rel="noreferrer">Get Directions</a><Link to={`/${spa.slug}` as "/ganga-spa"}>View Spa</Link></div></div></article>; })}</div>; }

export function Testimonials() { const quotes = ["A beautiful experience from beginning to end. The ambience and service made the entire visit incredibly relaxing.","Everything felt thoughtfully designed, from the atmosphere to the treatment. A truly calming experience.","A peaceful escape from the everyday. I left feeling completely refreshed."]; const [active, setActive] = useState(0); return <section className="section bg-beige"><div className="container-shell text-center"><SectionHeading eyebrow="Guest Experiences" title="Moments That Stay With You" align="center"/><div className="mx-auto mt-12 max-w-3xl"><p aria-label="Five stars" className="text-lg tracking-[0.3em] text-gold">★★★★★</p><blockquote className="mt-7 font-serif text-3xl leading-snug text-primary sm:text-4xl">“{quotes[active]}”</blockquote><p className="mt-6 text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">Guest Experience · Rajkot</p><div className="mt-8 flex justify-center gap-3"><button aria-label="Previous testimonial" className="carousel-button" onClick={() => setActive((active + 2) % 3)}><ChevronLeft /></button><button aria-label="Next testimonial" className="carousel-button" onClick={() => setActive((active + 1) % 3)}><ChevronRight /></button></div></div></div></section>; }

export function GalleryGrid({ compact = false }: { compact?: boolean }) { const set = [images.hero, images.hammam, images.treatment, images.details, images.treatment, images.hero, images.details, images.hammam, images.hero]; return <div className="mt-14 columns-1 gap-4 sm:columns-2 lg:columns-3">{set.slice(0, compact ? 6 : 9).map((src, i) => <figure key={i} className="group relative mb-4 break-inside-avoid overflow-hidden rounded-[1.75rem]"><img src={src} alt={["Luxury spa interior", "Moroccan hammam", "Wellness massage treatment", "Natural spa details"][i % 4]} loading="lazy" className={`w-full object-cover transition-transform duration-700 group-hover:scale-[1.03] ${i % 3 === 1 ? "aspect-[4/5]" : i % 3 === 2 ? "aspect-square" : "aspect-[4/3]"}`} /><figcaption className="absolute inset-0 flex items-end bg-foreground/0 p-6 text-[0.65rem] font-medium uppercase tracking-[0.18em] text-background opacity-0 transition-all duration-500 group-hover:bg-foreground/30 group-hover:opacity-100">View Image</figcaption></figure>)}</div>; }

export function FinalCta({ onBook }: { onBook: () => void }) { return <section className="section"><div className="container-shell"><div className="relative overflow-hidden rounded-[2.75rem] bg-primary px-6 py-20 text-primary-foreground sm:py-28"><div className="leaf-outline absolute -right-20 -top-24 opacity-10"/><div className="container-shell relative text-center"><Sparkles className="mx-auto mb-6 size-6 text-gold"/><h2 className="font-serif text-4xl sm:text-6xl">Your Time to Unwind Starts Here.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-primary-foreground/75">Choose your spa, choose your experience and make time for yourself.</p><Button variant="gold" className="mt-8" onClick={onBook}>Book Your Experience</Button></div></div></div></section>; }
