import * as Dialog from "@radix-ui/react-dialog";
import { ArrowDown, ArrowRight, Clock3, ExternalLink, Facebook, Instagram, MapPin, MessageCircle, Phone, Play, X } from "lucide-react";
import { useState } from "react";
import { Button } from "./Button";
import { Reveal } from "./Reveal";
import { Eyebrow, SectionHeading } from "./Sections";
import type { Spa } from "@/data/site";

export function SpaDetailPage({ spa }: { spa: Spa }) {
  const [booking, setBooking] = useState(false);
  const [lightbox, setLightbox] = useState<string | null>(null);
  const verified = spa.contactVerified === true;
  const galleryVerified = spa.galleryVerified === true;
  const treatmentGroups = Array.from(new Set(spa.treatments.map((item) => item.category ?? "Treatment Menu")));
  const whatsapp = `https://wa.me/${spa.phone.replace(/\D/g, "")}?text=${encodeURIComponent(`Hello ${spa.name}, I would like to book a wellness experience.`)}`;
  return <div className={`spa-detail ${spa.tone}`}>
    <section className="relative min-h-screen overflow-hidden">
      <img src={spa.heroImage} alt={`${spa.name} wellness interior`} className="absolute inset-0 size-full object-cover" />
      <div className="absolute inset-0 bg-gradient-to-t from-primary/90 via-primary/35 to-primary/15" />
      <div className="container-shell relative flex min-h-screen items-end pb-20 pt-36">
        <Reveal className="max-w-4xl text-primary-foreground"><p className="mt-7 text-xs uppercase tracking-[0.24em]">An ADWITYA WELLNESS destination</p><h1 className="mt-4 font-serif text-6xl leading-none sm:text-8xl lg:text-9xl">{spa.name}</h1><p className="mt-5 max-w-xl font-serif text-2xl italic sm:text-3xl">{spa.tagline}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button variant="gold" onClick={() => setBooking(true)}>Book Now</Button><Button className="border border-primary-foreground/40 bg-primary-foreground/10 text-primary-foreground backdrop-blur hover:bg-primary-foreground hover:text-primary" asChild><a href="#treatments">Explore Treatments</a></Button></div></Reveal>
      </div><a href="#about" aria-label={`Scroll to about ${spa.name}`} className="absolute bottom-7 right-7 grid size-12 place-items-center rounded-full border border-primary-foreground/40 text-primary-foreground"><ArrowDown className="size-4" /></a>
    </section>

    <section id="about" className="section"><div className="container-shell grid items-center gap-14 lg:grid-cols-12"><Reveal className="lg:col-span-5"><SectionHeading eyebrow="About the spa" title={`About ${spa.name}`} text={spa.description}/></Reveal><Reveal className="lg:col-span-7" delay={120}><div className="grid grid-cols-2 gap-4">{(spa.aboutImages ?? [spa.galleryImages[1], spa.galleryImages[2]]).map((src, index)=><img key={index} src={src} alt={`${spa.name} ${index===0 ? "wellness space" : "treatment room"}`} className={`media-frame w-full object-cover ${index===0?"h-96":"mt-14 h-80"}`}/>)}</div></Reveal></div></section>

    <section id="treatments" className="section bg-muted/60">
      <div className="container-shell">
        <Reveal><SectionHeading eyebrow="Treatment menu" title="Our Treatments" text="Explore our signature therapies. Timings and pricing are shared by the spa on request."/></Reveal>
        <div className="mt-14 space-y-16">{treatmentGroups.map((category)=>
          <div key={category}>
            <Reveal><div className="flex items-center gap-5"><h3 className="shrink-0 font-serif text-3xl text-primary sm:text-4xl">{category}</h3><span className="h-px w-full bg-border"/></div></Reveal>
            <div className="mt-8 grid gap-6 sm:grid-cols-2 xl:grid-cols-3">{spa.treatments.filter((item)=>(item.category ?? "Treatment Menu")===category).map((item)=>{
              const index = spa.treatments.indexOf(item);
              return <Reveal key={item.name} delay={(index%3)*70}>
                <article className="group flex h-full flex-col overflow-hidden rounded-[1.75rem] border border-border/70 bg-background transition-all duration-500 hover:-translate-y-1 hover:border-gold/40 hover:shadow-[0_24px_60px_-40px_rgb(0_0_0/0.45)]">
                  <div className="relative aspect-[4/3] overflow-hidden">
                    <img src={item.image ?? spa.heroImage} alt={`${item.name} treatment at ${spa.name}`} loading="lazy" width={1536} height={1024} className="absolute inset-0 size-full object-cover transition-transform duration-700 group-hover:scale-[1.06]"/>
                    <div className="absolute inset-0 bg-gradient-to-t from-primary/55 via-primary/5 to-transparent opacity-80"/>
                  </div>
                  <div className="flex min-w-0 flex-1 flex-col p-6">
                    <h4 className="font-serif text-2xl leading-tight text-primary">{item.name}</h4>
                    <p className="mt-3 text-sm leading-7 text-muted-foreground">{item.description}</p>
                    <div className="mt-6 flex flex-wrap items-center gap-2 text-[0.68rem] uppercase tracking-[0.14em] text-muted-foreground">
                      <span className="inline-flex items-center gap-1.5 rounded-full border border-border px-3 py-1.5"><Clock3 className="size-3.5 text-gold"/>{item.duration}</span>
                      <span className="inline-flex items-center gap-1.5 rounded-full border border-border px-3 py-1.5">{item.price}</span>
                    </div>
                    <div className="mt-auto pt-6">
                      <button type="button" onClick={()=>setBooking(true)} className="inline-flex items-center gap-2 text-[0.7rem] font-medium uppercase tracking-[0.18em] text-primary transition-colors hover:text-gold">Book this treatment <ArrowRight className="size-4 transition-transform duration-300 group-hover:translate-x-1"/></button>
                    </div>
                  </div>
                </article>
              </Reveal>;
            })}</div>
          </div>
        )}</div>
      </div>
    </section>

    <section className="section"><div className="container-shell grid gap-10 lg:grid-cols-[1fr_1.15fr]"><Reveal><Eyebrow>{`Our location · ${spa.location}`}</Eyebrow><h2 className="section-title mt-3">Find {spa.name}</h2><p className="mt-6 max-w-md text-base leading-8 text-muted-foreground">{verified ? `A peaceful wellness escape in ${spa.location}, easy to reach and thoughtfully tucked away from the everyday rush.` : `A peaceful wellness escape in ${spa.location}.`}</p><p className="mt-7 flex max-w-md items-start gap-3 text-sm leading-7"><MapPin className="mt-1 size-4 shrink-0 text-gold"/>{spa.address}</p><Button variant="outline" className="mt-8" asChild><a href={spa.googleMapsUrl} target="_blank" rel="noreferrer">Open in Google Maps <ExternalLink className="size-4"/></a></Button></Reveal><Reveal delay={100}><a href={spa.googleMapsUrl} target="_blank" rel="noreferrer" aria-label={`Open ${spa.name} location in Google Maps`} className="group relative block min-h-96 overflow-hidden rounded-[2rem] bg-sage transition-shadow duration-300 hover:shadow-elevated focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary"><div className="absolute inset-0 opacity-40 map-pattern"/><div className="absolute inset-0 grid place-items-center"><div className="glass-panel max-w-xs p-6 text-center transition-transform duration-300 group-hover:-translate-y-1"><MapPin className="mx-auto size-7 text-primary"/><p className="mt-3 font-serif text-2xl text-primary">{spa.location}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">Tap here to open turn-by-turn directions in Google Maps.</p></div></div></a></Reveal></div></section>

    <section className="section bg-primary text-primary-foreground"><div className="container-shell"><Reveal><p className="eyebrow">Guest experiences</p><h2 className="mt-3 max-w-3xl font-serif text-5xl sm:text-7xl">What Our Guests Say</h2></Reveal><div className="mt-14 grid gap-8 md:grid-cols-3">{spa.reviews.map((review,index)=><Reveal key={review.guest} delay={index*90}><figure className="border-t border-primary-foreground/25 pt-7"><p aria-label="Five stars" className="text-gold">★★★★★</p><blockquote className="mt-6 font-serif text-2xl leading-snug">“{review.quote}”</blockquote><figcaption className="mt-7 text-xs uppercase tracking-[0.16em] text-primary-foreground/60">{review.guest}</figcaption></figure></Reveal>)}</div></div></section>

    <section className="section"><div className="container-shell"><Reveal><SectionHeading eyebrow="Our space" title={`Inside ${spa.name}`} text={`Explore the reception, lounge and treatment spaces at ${spa.name}.`}/></Reveal><div className="mt-12 flex snap-x gap-4 overflow-x-auto pb-4 sm:grid sm:grid-cols-2 sm:overflow-visible lg:grid-cols-3">{spa.galleryImages.map((src,index)=><button key={index} onClick={()=>setLightbox(src)} aria-label={`Open ${spa.name} gallery image ${index+1}`} className="group relative min-w-[82vw] snap-center overflow-hidden rounded-[1.75rem] sm:min-w-0"><img src={src} alt={`${spa.name} interior ${index+1}`} className={`w-full object-cover transition-transform duration-700 group-hover:scale-105 ${index%3===1?"aspect-[4/5]":"aspect-[4/3]"}`}/></button>)}</div></div></section>

    <section className="section bg-beige"><div className="container-shell grid items-center gap-12 lg:grid-cols-2"><Reveal><Eyebrow>Follow us</Eyebrow><h2 className="section-title mt-3">Follow {spa.name}</h2><p className="mt-5 font-serif text-2xl italic text-primary">{spa.instagram}</p><p className="mt-4 max-w-md leading-7 text-muted-foreground">See our latest spaces, treatments and quiet everyday moments on Instagram.</p>{spa.instagramUrl ? <Button variant="outline" className="mt-8" asChild><a href={spa.instagramUrl} target="_blank" rel="noreferrer">Follow on Instagram <ExternalLink className="size-4"/></a></Button> : <Button variant="outline" className="mt-8">Follow on Instagram <Instagram className="size-4"/></Button>}</Reveal><div className="grid grid-cols-3 gap-3">{spa.galleryImages.slice(0,6).map((src,index)=><img key={index} src={src} alt={`${spa.name} social preview ${index+1}`} className="aspect-square w-full rounded-xl object-cover"/>)}</div></div></section>

    <section className="section"><div className="container-shell grid items-center gap-12 lg:grid-cols-2"><Reveal><Eyebrow>Spa reel</Eyebrow><h2 className="section-title mt-3">Experience {spa.name}</h2><p className="mt-5 max-w-md leading-8 text-muted-foreground">A short cinematic look inside the spa.</p></Reveal><Reveal className={spa.reelUrl2 ? "mx-auto w-full max-w-3xl" : "mx-auto w-full max-w-sm"} delay={100}><div className={spa.reelUrl2 ? "grid gap-6 sm:grid-cols-2" : undefined}>{spa.reelUrl ? <video controls playsInline preload="metadata" poster={spa.reelPoster} aria-label={`${spa.name} reel`} className="aspect-[9/16] w-full overflow-hidden rounded-[2rem] object-cover"><source src={spa.reelUrl} type="video/mp4"/></video> : <button aria-label={`Play ${spa.name} reel`} className="group relative aspect-[9/16] w-full overflow-hidden rounded-[2rem]"><img src={spa.heroImage} alt={`${spa.name} reel poster`} className="size-full object-cover transition-transform duration-700 group-hover:scale-105"/><span className="absolute inset-0 bg-primary/25"/><span className="absolute inset-0 grid place-items-center"><span className="grid size-20 place-items-center rounded-full bg-background/85 text-primary backdrop-blur"><Play className="ml-1 size-7"/></span></span></button>}{spa.reelUrl2 ? <video controls playsInline preload="metadata" poster={spa.reelPoster2} aria-label={`${spa.name} reel two`} className="aspect-[9/16] w-full overflow-hidden rounded-[2rem] object-cover"><source src={spa.reelUrl2} type="video/mp4"/></video> : null}</div></Reveal></div></section>

    <section className="section bg-sage"><div className="container-shell grid gap-12 lg:grid-cols-2"><Reveal><SectionHeading eyebrow="Contact details" title={`Connect With ${spa.name}`} text="Reach out directly by phone or WhatsApp, or visit us at the address below. Tap the phone number to call us directly."/><Button className="mt-8" onClick={()=>setBooking(true)}>Book Your Experience</Button></Reveal><dl className="grid gap-px overflow-hidden rounded-[2rem] border border-border bg-border sm:grid-cols-2">{[[Phone,"Phone",spa.phone,`tel:${spa.phone.replace(/\s/g,"")}`],[Facebook,"Facebook","Follow us on Facebook",spa.facebookUrl],[MapPin,"Address",spa.address,spa.googleMapsUrl],[Clock3,"Opening hours",spa.hours,null]].map(([Icon,label,value,href])=>{const C=Icon as typeof Phone; const isTel=(href as string|null)?.startsWith("tel:"); const inner=<><C className="size-5 text-gold"/><dt className="mt-6 text-xs uppercase tracking-[0.16em] text-muted-foreground">{label as string}</dt><dd className="mt-2 text-sm leading-6 text-primary">{value as string}</dd></>; return href ? <a key={label as string} href={href as string} {...(isTel ? {} : {target:"_blank",rel:"noreferrer"})} className="group relative block bg-background p-7 transition-colors duration-300 hover:bg-sage/60">{inner}<ArrowRight className="absolute right-6 top-7 size-4 text-muted-foreground opacity-0 transition-opacity duration-300 group-hover:opacity-100"/></a> : <div key={label as string} className="bg-background p-7">{inner}</div>;})}</dl></div></section>

    <div className="fixed inset-x-3 bottom-3 z-40 grid grid-cols-3 gap-2 rounded-2xl border border-border/60 bg-background/90 p-2 shadow-elevated backdrop-blur-xl lg:hidden"><Button variant="ghost" asChild><a href={`tel:${spa.phone.replace(/\s/g,"")}`}><Phone className="size-4"/>Call</a></Button><Button variant="outline" asChild><a href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle className="size-4"/>WhatsApp</a></Button><Button onClick={()=>setBooking(true)}>Book</Button></div>
    <BookingActions open={booking} onOpenChange={setBooking} spa={spa} whatsapp={whatsapp} verified={verified}/>
    <Dialog.Root open={Boolean(lightbox)} onOpenChange={(open)=>!open&&setLightbox(null)}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-primary/85 backdrop-blur-md"/><Dialog.Content className="fixed inset-4 z-50 grid place-items-center focus:outline-none"><Dialog.Title className="sr-only">{spa.name} gallery image</Dialog.Title>{lightbox&&<img src={lightbox} alt={`${spa.name} enlarged gallery view`} className="max-h-[88vh] max-w-full rounded-2xl object-contain"/>}<Dialog.Close asChild><button aria-label="Close image" className="absolute right-2 top-2 grid size-12 place-items-center rounded-full bg-background text-primary"><X/></button></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>
  </div>;
}

function BookingActions({open,onOpenChange,spa,whatsapp,verified}:{open:boolean;onOpenChange:(open:boolean)=>void;spa:Spa;whatsapp:string;verified:boolean}) { return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-primary/60 backdrop-blur-sm"/><Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-[2rem] bg-background p-7 shadow-elevated focus:outline-none sm:p-10"><Dialog.Close asChild><button aria-label="Close booking options" className="absolute right-4 top-4 grid size-11 place-items-center rounded-full text-primary hover:bg-muted"><X className="size-5"/></button></Dialog.Close><Dialog.Title className="mt-6 font-serif text-4xl text-primary">Book Your {spa.name} Experience</Dialog.Title><Dialog.Description className="mt-4 leading-7 text-muted-foreground">Choose how you would like to connect — call or WhatsApp us directly on the number below.</Dialog.Description><p className="mt-6 font-serif text-2xl text-primary">{spa.phone}</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><Button asChild><a href={`tel:${spa.phone.replace(/\s/g,"")}`}><Phone className="size-4"/>Call Now</a></Button><Button variant="outline" asChild><a href={whatsapp} target="_blank" rel="noreferrer"><MessageCircle className="size-4"/>WhatsApp Us</a></Button></div></Dialog.Content></Dialog.Portal></Dialog.Root> }
