/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmoreWellnessRouteImport } from './routes/amore-wellness'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GangaSpaRouteImport } from './routes/ganga-spa'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as MottoRouteImport } from './routes/motto'
import { Route as OurSpasRouteImport } from './routes/our-spas'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as ReasonRouteImport } from './routes/reason'
import { Route as SattvaWellnessRouteImport } from './routes/sattva-wellness'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmoreWellnessRoute = AmoreWellnessRouteImport.update({
  id: '/amore-wellness',
  path: '/amore-wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GangaSpaRoute = GangaSpaRouteImport.update({
  id: '/ganga-spa',
  path: '/ganga-spa',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const MottoRoute = MottoRouteImport.update({
  id: '/motto',
  path: '/motto',
  getParentRoute: () => rootRouteImport,
} as any)
const OurSpasRoute = OurSpasRouteImport.update({
  id: '/our-spas',
  path: '/our-spas',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReasonRoute = ReasonRouteImport.update({
  id: '/reason',
  path: '/reason',
  getParentRoute: () => rootRouteImport,
} as any)
const SattvaWellnessRoute = SattvaWellnessRouteImport.update({
  id: '/sattva-wellness',
  path: '/sattva-wellness',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amore-wellness': typeof AmoreWellnessRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/ganga-spa': typeof GangaSpaRoute
  '/locations': typeof LocationsRoute
  '/motto': typeof MottoRoute
  '/our-spas': typeof OurSpasRoute
  '/philosophy': typeof PhilosophyRoute
  '/reason': typeof ReasonRoute
  '/sattva-wellness': typeof SattvaWellnessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amore-wellness': typeof AmoreWellnessRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/ganga-spa': typeof GangaSpaRoute
  '/locations': typeof LocationsRoute
  '/motto': typeof MottoRoute
  '/our-spas': typeof OurSpasRoute
  '/philosophy': typeof PhilosophyRoute
  '/reason': typeof ReasonRoute
  '/sattva-wellness': typeof SattvaWellnessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amore-wellness': typeof AmoreWellnessRoute
  '/contact': typeof ContactRoute
  '/experiences': typeof ExperiencesRoute
  '/gallery': typeof GalleryRoute
  '/ganga-spa': typeof GangaSpaRoute
  '/locations': typeof LocationsRoute
  '/motto': typeof MottoRoute
  '/our-spas': typeof OurSpasRoute
  '/philosophy': typeof PhilosophyRoute
  '/reason': typeof ReasonRoute
  '/sattva-wellness': typeof SattvaWellnessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amore-wellness'
    | '/contact'
    | '/experiences'
    | '/gallery'
    | '/ganga-spa'
    | '/locations'
    | '/motto'
    | '/our-spas'
    | '/philosophy'
    | '/reason'
    | '/sattva-wellness'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amore-wellness'
    | '/contact'
    | '/experiences'
    | '/gallery'
    | '/ganga-spa'
    | '/locations'
    | '/motto'
    | '/our-spas'
    | '/philosophy'
    | '/reason'
    | '/sattva-wellness'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amore-wellness'
    | '/contact'
    | '/experiences'
    | '/gallery'
    | '/ganga-spa'
    | '/locations'
    | '/motto'
    | '/our-spas'
    | '/philosophy'
    | '/reason'
    | '/sattva-wellness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmoreWellnessRoute: typeof AmoreWellnessRoute
  ContactRoute: typeof ContactRoute
  ExperiencesRoute: typeof ExperiencesRoute
  GalleryRoute: typeof GalleryRoute
  GangaSpaRoute: typeof GangaSpaRoute
  LocationsRoute: typeof LocationsRoute
  MottoRoute: typeof MottoRoute
  OurSpasRoute: typeof OurSpasRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ReasonRoute: typeof ReasonRoute
  SattvaWellnessRoute: typeof SattvaWellnessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amore-wellness': {
      id: '/amore-wellness'
      path: '/amore-wellness'
      fullPath: '/amore-wellness'
      preLoaderRoute: typeof AmoreWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ganga-spa': {
      id: '/ganga-spa'
      path: '/ganga-spa'
      fullPath: '/ganga-spa'
      preLoaderRoute: typeof GangaSpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motto': {
      id: '/motto'
      path: '/motto'
      fullPath: '/motto'
      preLoaderRoute: typeof MottoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-spas': {
      id: '/our-spas'
      path: '/our-spas'
      fullPath: '/our-spas'
      preLoaderRoute: typeof OurSpasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reason': {
      id: '/reason'
      path: '/reason'
      fullPath: '/reason'
      preLoaderRoute: typeof ReasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sattva-wellness': {
      id: '/sattva-wellness'
      path: '/sattva-wellness'
      fullPath: '/sattva-wellness'
      preLoaderRoute: typeof SattvaWellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmoreWellnessRoute: AmoreWellnessRoute,
  ContactRoute: ContactRoute,
  ExperiencesRoute: ExperiencesRoute,
  GalleryRoute: GalleryRoute,
  GangaSpaRoute: GangaSpaRoute,
  LocationsRoute: LocationsRoute,
  MottoRoute: MottoRoute,
  OurSpasRoute: OurSpasRoute,
  PhilosophyRoute: PhilosophyRoute,
  ReasonRoute: ReasonRoute,
  SattvaWellnessRoute: SattvaWellnessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
